# segmentation:
#   ros__parameters:
#     distance_threshold: 0.10
#     max_avg_distance_from_sensor: 3.0
#     max_points_segment: 100
#     max_segment_width: 0.2
#     method_threshold: ''
#     min_avg_distance_from_sensor: 0.0
#     min_points_segment: 1
#     min_segment_width: 0.1
#     noise_reduction: 0.3
#     restore_defaults: false
#     scan_topic: scan
#     segmentation_type: jump_distance
#     segments_topic: segments


segmentation:
  ros__parameters:
    distance_threshold: 0.10
    max_avg_distance_from_sensor: 3.0
    max_points_segment: 100
    max_segment_width: 0.2
    method_threshold: ''
    min_avg_distance_from_sensor: 0.0
    min_points_segment: 20
    min_segment_width: 0.1
    noise_reduction: 0.7
    restore_defaults: false
    scan_topic: scan
    segmentation_type: jump_distance
    segments_topic: segments

# segmentation:
#   ros__parameters:
#     distance_threshold: 0.10
#     max_avg_distance_from_sensor: 2.0
#     max_points_segment: 100
#     max_segment_width: 0.2
#     method_threshold: ''
#     min_avg_distance_from_sensor: 0.0
#     min_points_segment: 15
#     min_segment_width: 0.1
#     noise_reduction: 0.3
#     restore_defaults: false
#     scan_topic: scan
#     segmentation_type: jump_distance
#     segments_topic: segments


